{% set name = "ipywidgets-jsonschema" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_jsonschema-{{ version }}.tar.gz
  sha256: 1a7265209c3c364b7281d5ab90cd333a71d65cfc2440742439a098aa5b6715a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ipython
    - ipywidgets
    - jsonschema <5.0a0
    - packaging
    - python >={{ python_min }}
    - traitlets

test:
  imports:
    - ipywidgets_jsonschema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ipywidgets-jsonschema/
  summary: Widget Generator for JSON schema
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
