{% set name = "ipywidgets-jsonschema" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_jsonschema-{{ version }}.tar.gz
  sha256: 40cf13da435eb66f0ca64fee5ed271982ebcb16db4f86b54e6a304c37675ba52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipython
    - ipywidgets
    - jsonschema <5.0a0
    - packaging
    - python >=3.7
    - traitlets

test:
  imports:
    - ipywidgets_jsonschema
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ipywidgets-jsonschema/
  summary: Widget Generator for JSON schema
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
