{% set name = "ipywidgets-jsonschema" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_jsonschema-{{ version }}.tar.gz
  sha256: 2f827bd2ca987566af0c888853c1cf3afc163346a887b31a787e32a8d6c75245

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipython
    - ipywidgets
    - jsonschema <4
    - packaging
    - python >=3.7
    - traitlets

test:
  imports:
    - ipywidgets_jsonschema
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ipywidgets-jsonschema/
  summary: Widget Generator for JSON schema
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
