{% set name = "ipywidgets-jsonschema" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_jsonschema-{{ version }}.tar.gz
  sha256: 225636b8d2c9b0f7d766892d2dc11e4174bb02dee3a7b9869f6e96f5af80497c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ipython
    - ipywidgets
    - jsonschema <5.0a0
    - packaging
    - python >={{ python_min }}
    - traitlets

test:
  imports:
    - ipywidgets_jsonschema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ipywidgets-jsonschema/
  summary: Widget Generator for JSON schema
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
