{% set name = "ipywidgets-jsonschema" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_jsonschema-{{ version }}.tar.gz
  sha256: 34caa13b1ff0161772d74dff4e2a2919fdf62699ca05a99090549754117b0a6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ipython
    - ipywidgets
    - jsonschema <5.0a0
    - packaging
    - python >={{ python_min }}
    - traitlets

test:
  imports:
    - ipywidgets_jsonschema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ipywidgets-jsonschema/
  summary: Widget Generator for JSON schema
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
